{application,pb_getter,
             [{applications,[kernel,stdlib,elixir,logger,httpoison,floki]},
              {description,"pb_getter"},
              {modules,['Elixir.PbGetter','Elixir.PbGetter.Pb_Args',
                        'Elixir.PbGetter.Pb_Get','Elixir.PbGetter.Pb_Output',
                        'Elixir.PbGetter.Pb_URL']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger]}]}.
